# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import centralStorage_pb2 as centralStorage__pb2


class CentralRegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/CentralRegistry/Register',
                request_serializer=centralStorage__pb2.ServerInfo.SerializeToString,
                response_deserializer=centralStorage__pb2.RegisterResponse.FromString,
                )
        self.MapKey = channel.unary_unary(
                '/CentralRegistry/MapKey',
                request_serializer=centralStorage__pb2.KeyRequest.SerializeToString,
                response_deserializer=centralStorage__pb2.MappingResponse.FromString,
                )
        self.Terminate = channel.unary_unary(
                '/CentralRegistry/Terminate',
                request_serializer=centralStorage__pb2.Empty.SerializeToString,
                response_deserializer=centralStorage__pb2.TerminateResponse.FromString,
                )


class CentralRegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MapKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=centralStorage__pb2.ServerInfo.FromString,
                    response_serializer=centralStorage__pb2.RegisterResponse.SerializeToString,
            ),
            'MapKey': grpc.unary_unary_rpc_method_handler(
                    servicer.MapKey,
                    request_deserializer=centralStorage__pb2.KeyRequest.FromString,
                    response_serializer=centralStorage__pb2.MappingResponse.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=centralStorage__pb2.Empty.FromString,
                    response_serializer=centralStorage__pb2.TerminateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CentralRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CentralRegistry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CentralRegistry/Register',
            centralStorage__pb2.ServerInfo.SerializeToString,
            centralStorage__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MapKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CentralRegistry/MapKey',
            centralStorage__pb2.KeyRequest.SerializeToString,
            centralStorage__pb2.MappingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CentralRegistry/Terminate',
            centralStorage__pb2.Empty.SerializeToString,
            centralStorage__pb2.TerminateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
