# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: centralStorage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x65ntralStorage.proto\"-\n\nServerInfo\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\x05\"\x19\n\nKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"*\n\x10RegisterResponse\x12\x16\n\x0eprocessed_keys\x18\x01 \x01(\x05\"$\n\x0fMappingResponse\x12\x11\n\tserver_id\x18\x01 \x01(\t\"#\n\x11TerminateResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\x8f\x01\n\x0f\x43\x65ntralRegistry\x12*\n\x08Register\x12\x0b.ServerInfo\x1a\x11.RegisterResponse\x12\'\n\x06MapKey\x12\x0b.KeyRequest\x1a\x10.MappingResponse\x12\'\n\tTerminate\x12\x06.Empty\x1a\x12.TerminateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'centralStorage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVERINFO']._serialized_start=24
  _globals['_SERVERINFO']._serialized_end=69
  _globals['_KEYREQUEST']._serialized_start=71
  _globals['_KEYREQUEST']._serialized_end=96
  _globals['_REGISTERRESPONSE']._serialized_start=98
  _globals['_REGISTERRESPONSE']._serialized_end=140
  _globals['_MAPPINGRESPONSE']._serialized_start=142
  _globals['_MAPPINGRESPONSE']._serialized_end=178
  _globals['_TERMINATERESPONSE']._serialized_start=180
  _globals['_TERMINATERESPONSE']._serialized_end=215
  _globals['_EMPTY']._serialized_start=217
  _globals['_EMPTY']._serialized_end=224
  _globals['_CENTRALREGISTRY']._serialized_start=227
  _globals['_CENTRALREGISTRY']._serialized_end=370
# @@protoc_insertion_point(module_scope)
