all:
	python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. storage.proto

# run_serv_pares_1:
#      ./svc_par $(arg)
# run_serv_pares_2:
#      ./svc_par $(arg) qqcoisa  # como descrito, o segundo argumento só tem que existir
# run_cli_pares:
#      ./cln_par $(arg)
# run_serv_central:
#      ./svc_cen $(arg)
# run_cli_central:
#      ./cln_cen $(arg)