# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\rKeyValueStore\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\'\n\x11\x41\x63tivationRequest\x12\x12\n\nservice_id\x18\x01 \x01(\t\" \n\x0eInsertResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1e\n\rQueryResponse\x12\r\n\x05value\x18\x01 \x01(\t\"#\n\x12\x41\x63tivationResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"\x11\n\x0fTerminateParams\"#\n\x11TerminateResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xac\x02\n\rKeyValueStore\x12@\n\x06Insert\x12\x17.KeyValueStore.KeyValue\x1a\x1d.KeyValueStore.InsertResponse\x12\x39\n\x05Query\x12\x12.KeyValueStore.Key\x1a\x1c.KeyValueStore.QueryResponse\x12O\n\x08\x41\x63tivate\x12 .KeyValueStore.ActivationRequest\x1a!.KeyValueStore.ActivationResponse\x12M\n\tTerminate\x12\x1e.KeyValueStore.TerminateParams\x1a .KeyValueStore.TerminateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KEYVALUE']._serialized_start=32
  _globals['_KEYVALUE']._serialized_end=70
  _globals['_KEY']._serialized_start=72
  _globals['_KEY']._serialized_end=90
  _globals['_ACTIVATIONREQUEST']._serialized_start=92
  _globals['_ACTIVATIONREQUEST']._serialized_end=131
  _globals['_INSERTRESPONSE']._serialized_start=133
  _globals['_INSERTRESPONSE']._serialized_end=165
  _globals['_QUERYRESPONSE']._serialized_start=167
  _globals['_QUERYRESPONSE']._serialized_end=197
  _globals['_ACTIVATIONRESPONSE']._serialized_start=199
  _globals['_ACTIVATIONRESPONSE']._serialized_end=234
  _globals['_TERMINATEPARAMS']._serialized_start=236
  _globals['_TERMINATEPARAMS']._serialized_end=253
  _globals['_TERMINATERESPONSE']._serialized_start=255
  _globals['_TERMINATERESPONSE']._serialized_end=290
  _globals['_KEYVALUESTORE']._serialized_start=293
  _globals['_KEYVALUESTORE']._serialized_end=593
# @@protoc_insertion_point(module_scope)
